### ISSUE TITLE
Errors squashing some already minified sources

### ISSUE THREAD

**Issue by Loilo** [Rich-Harris/butternut#82] opened 2017-05-14 21:35 UTC
I've already encountered those problems with UglifyJS: Running a minifier on some already minfied libraries fails. This also happens with here.

So I tested Butternut regarding that concern with the minified codebases (from cdnjs) of jQuery, Angular, React and Vue.

It throw errors [with Angular.js (1.6)](https://butternut.now.sh/?version=0.4.1&gist=663e197bf89323f83c87f463c4573a5a) (so does UglifyJS) and [with Vue.js](https://butternut.now.sh/?version=0.4.1&gist=6dead88f8da99262fe8a26ec7813dde2).

**Comment by kzc** [comment] 2017-05-15 03:17
Smaller repro:
```
$ cat t.js
for(m=d.length;l<m;l++)if(d[l])try{d[l].apply(null,k)}catch(n){e(n)}else d.splice(l,1),l--,m--;
```
```
$ bin/squash t.js
for(m=d.length;l<m;l++)if(d[l])try{d[l].apply(null,k)}catch(a){e(a)};else d.splice(l,1),l--,m--
```
The problem is that butternut emits a semicolon before the else: `;else`
```
$ bin/squash t.js --check
Butternut generated invalid JS: code in source file near (1:73) became
...{d[l].apply(null,k)}catch(a){e(a)};else d.splice(l,1),l--,m--...
SyntaxError: Butternut generated invalid JS: code in source file near (1:73) became
...{d[l].apply(null,k)}catch(a){e(a)};else d.splice(l,1),l--,m--...
```

Butternut works correctly on beautified uglify output:
```
$ uglifyjs t.js -b bracketize
for (m = d.length; l < m; l++) {
    if (d[l]) {
        try {
            d[l].apply(null, k);
        } catch (n) {
            e(n);
        }
    } else {
        d.splice(l, 1), l--, m--;
    }
}
```
```
$ uglifyjs t.js -b bracketize | bin/squash --check
for(m=d.length;l<m;l++){if(d[l]){try{d[l].apply(null,k)}catch(a){e(a)}}else d.splice(l,1), l--, m--}
```

I can't repro the problem of uglify'ing already minified code but if you can please open an issue on that project.

```
$ wget https://gist.githubusercontent.com/anonymous/663e197bf89323f83c87f463c4573a5a/raw/a43bf7587f48522b1f40f721f9ea699a710dd7c6/input.js

$ wc -c input.js
  166021 input.js

$ uglifyjs -V
3.0.4

$ uglifyjs input.js -cm | uglifyjs -cm | uglifyjs -cm | wc -c
  164824

$ uglifyjs input.js -cm | uglifyjs -cm | uglifyjs -cm | node_modules/.bin/acorn --silent

$ echo $?
0
```

**Comment by kzc** [comment] 2017-05-15 03:46
@Rich-Harris did you intend to output the original code location in the event of `--check` error rather than outputting the generated code twice?
```
$ bin/squash t.js --check
Butternut generated invalid JS: code in source file near (1:73) became
...{d[l].apply(null,k)}catch(a){e(a)};else d.splice(l,1),l--,m--...
SyntaxError: Butternut generated invalid JS: code in source file near (1:73) became
...{d[l].apply(null,k)}catch(a){e(a)};else d.splice(l,1),l--,m--...
```

**Comment by Rich-Harris** [comment] 2017-05-15 14:23
@kzc ah yep, the CLI needs some love. Good catch, thanks (and also for the repro)

**Comment by Rich-Harris** [comment] 2017-05-15 17:05
These errors are now fixed, and the CLI gives more informative error messages as of 0.4.3. Thanks

**Closed by Rich-Harris** 2017-05-15 17:05 UTC
Labels: bug
