### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lili21** [Rich-Harris/butternut#192] opened 2017-08-05 02:56 UTC
```bash
The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string
/Users/markli/dev/napos/teemo-backup/node_modules/butternut/dist/butternut.cjs.js:1891
		return this.alternate.getLeftHandSide();
		                     ^

TypeError: Cannot read property 'getLeftHandSide' of null
```

the error message is kind of useless. You can't tell which part  of your codebase make that happened.

**Comment by nifgraup** [comment] 2017-08-07 15:51
duplicate of #172, already fixed on master

**Closed as completed** 2017-08-07 15:58 UTC
